version: "3.1"
services:
    frontend:
      command: production
      env_file: .env.production
      ports:
        - "${FRONTEND}:3000"

    backend:
      env_file: .env.production
      volumes:
        - /dev:/dev
      ports:
        - "${BACKEND}:${SERVER_PORT}"
    
    wswebcam_0:
      env_file: .env.production
      volumes:
        - /dev:/dev
      ports:
        - "${WEBCAM_0}:${SERVER_PORT}"
    
    marlin_0:
      env_file: .env.production
      volumes:
        - /dev:/dev
      ports:
        - "${MARLIN_0}:${SERVER_PORT}"

    mongo:
      env_file: .env.production
      volumes:
        - ./mongodb:/data/db
      ports:
        - "${MONGO}:27017"

    redis:
      env_file: .env.production
      ports:
        - "${REDIS}:6379"