version: "3.1"
services:
  
  frontend:
    container_name: frontend
    privileged: true
    image: test_front
    build:
      context: ./frontend/
    restart: always
    networks:
      - bind-network
      - default
    logging:
      options:
        max-size: 50m

networks: 
  bind-network:
    driver: bridge