
version: "3.1"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_c
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      # MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
        - mongo-compose-network
    volumes: 
      - ./data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_c
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: senha
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      # ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      # ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USER}
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASS}
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
    volumes: 
      - ./data:/data/db
      

  # api:
  #   image: sherensberk/ominis_interface:latest
  #   container_name: omnis
  #   restart: always
  #   env_file:
  #    - .env
  #   depends_on:
  #     - db
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   networks:
  #   - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge